### ISSUE TITLE
No info about reminders of Events

### ISSUE THREAD

**Issue by Cosmopal** [srv-twry/Student-Companion#15]
The events have a button about setting reminders. But neither Readme nor the app tell about how it will be done. Further, there is no place you can view or delete the reminders which are once set

**Comment by dr0pdb** [comment]
@Cosmopal I think it is very obvious to the user that the clock icon in the ```ContestDetailActivity``` screen is meant to set the reminder. 
Once the user sets the reminder, the clock icon changes and now the button serves to unset the reminder.
If you stilll think this is not sufficient then i am definitely open to suggestions on this. :smile:

**Comment by Cosmopal** [comment]
Sorry, My bad, 

By "how it will be done" i meant how the reminder will be given. Like custom notif, calendar event, email, or alarm etc; Though I now see that the option one would guess would be a notif.

I was looking for some kind of a list of all events I have turned on a reminder for, or some kind of marker in the card of such events in the main list. This is because at some point in the development this list may contain many more types of events apart from coding calendars. Also I didn't notice that icon change in my emulator, sorry.
