### ISSUE TITLE
Use Retrofit instead of Volley to make Network requests

### ISSUE THREAD

**Issue by dr0pdb** [srv-twry/Student-Companion#23]
Volley isn't an industry standard now, So i think we should move to using Retrofit to make Network requests.

**Comment by eXeeLD** [comment]
Hi , can i start working on this issue ?

**Comment by dr0pdb** [comment]
Yes, please go ahead.

**Comment by eXeeLD** [comment]
i opened a PR, thank you

**Comment by eXeeLD** [comment]
@srv-twry i redone my pull request, can you please check them

**Comment by dr0pdb** [comment]
@eXeeLD Yes i will check them when i get time :smile: 
It seems that you don't know how to automatically link an issue with a PR. [This](https://github.com/blog/1506-closing-issues-via-pull-requests) would be a good read.

**Comment by eXeeLD** [comment]
@srv-twry thank you a lot , i'm new to the contribution to open source stuff, i don't know a lot of things yet

**Comment by smoralb** [comment]
Hi! I would like to know if this issue is closed or it is still open. I would like to contribute in this project and I know how to work with Retrofit 2. I don't know if @eXeeLD would like to work together.

Thanks!

**Comment by dr0pdb** [comment]
Hi @smoralb this issue is done. I will merge the work done by @eXeeLD . Please find other issues to work on :)
