### ISSUE TITLE
Use Timber for logging

### ISSUE THREAD

**Issue by dr0pdb** [srv-twry/Student-Companion#25]
Currently we are using the logging component of Android SDK.
We should move to using Timber.

**Comment by eXeeLD** [comment]
I can take on it tomorow, asign me please

**Comment by Vanethos** [comment]
Added PR for this
https://github.com/srv-twry/My-Companion/pull/36

**Comment by arpitkushwaha** [comment]
Can I work on this issue ??

**Comment by dr0pdb** [comment]
Hey @arpitkushwaha , This issue is already resolved and should have been closed. Sorry about that.

**Comment by arpitkushwaha** [comment]
Its fine.
